### PR TITLE
Ctya replace external ip lookup

### PR DESCRIPTION
**Pull request by ctya**
Fix for issue https://github.com/devcoin/core/issues/48

showmyip.com is not around anymore

I changed the secondary lookup to use ifconfig.co instead of showmyip.org

### CODE REVIEW

**Comment by ctya** [comment]
That makes sense to me too.
I was only trying to be consistent :)
Can you merge it with the hostname please?

**Comment by ctya** [comment]
updated now

**Comment by develCuy** [comment]
Just seen the policy from ifconfig.co: ```Please limit automated requests to 1 request per minute. No guarantee is made for requests that exceed this limit. They may be rate-limited, with a 429 status code, or dropped entirely.```

There are thousands of nodes running devcoin, will this service be able to hold that much load?

**Comment by ctya** [comment]
Do you prefer
https://www.ipify.org

**Comment by emfox** [comment]
depend on an external service for a decentralized blockchain is not a good idea, I prefer switch the bitcoin way of UPnP.

https://bitcoin.stackexchange.com/questions/74730/how-do-bitcoin-nodes-know-their-own-external-ip-address

**Comment by develCuy** [comment]
@emfox you are right, please open a new issue for it. For now we'll just use a better external service.

**Pull request merged**
