### PR TITLE
added current payout round number to getinfo output

### PR DESCRIPTION
**Pull request by ctya**
added current payout round number to getinfo output

https://github.com/devcoin/core/issues/65

### CODE REVIEW

**Comment by develCuy** [comment]
@ctya great timing! I further improved your changes to use same calculation method as receiver.h
Now we need to test this!

**Comment by ctya** [comment]
Tested fine!

**Comment by develCuy** [comment]
@ctya, we need other person that you to certify the changes

**Comment by ctya** [comment]
ok, who?
I think it is just you and me at this point.

**Comment by cpsilent** [comment]
Ok, I succeeded to compile the wallet using this branch in one computer with a fresh installation of Kubuntu 18.04.1.  The other two computers are using the same version now, but they failed the compilation.  The only difference between them is that they were upgraded from 17.10 and 16.04.5 and they are probably carrying dependencies problems, but I reported that in the issue #56 so for this present pull let's forget about it.

In that way, what do you need exactly to check in this branch? That it compiles correctly or something else?

**Comment by develCuy** [comment]
Well done @ctya!

**Pull request merged**
