### PR TITLE
Update curl to version 7.61.0

### PR DESCRIPTION
**Pull request by ctya**
The old version of curl has a problem with timeouts causing a stack dump on some linux systems.
(*** longjmp causes uninitialized stack frame ***: )

The old version of curl certainly has many other bugs which have since been resolved.

This update removed the old src/curl with the latest release.
The makefile(s) which build curl also needed to be updated since this new version uses buildconf to automatically create the configure, so those are also updated here.

I did quality checking for builds on Windows, Ubuntu, Gentoo, Centos, and MacOSX and the builds all work well with the new version of curl.

### CODE REVIEW

**Comment by develCuy** [comment]
Amazing contribution ctya! Can I have the link to the curl source you used?

**Comment by ctya** [comment]
https://curl.haxx.se/download.html

**Comment by develCuy** [comment]
@ctya I downloaded curl from the official site and run a diff against your changes, to better understand them. I found too many differences, so I'm wondering if I'm using the same source as you. This is the file I downloaded:
https://curl.haxx.se/download/curl-7.61.0.tar.gz

**Comment by ctya** [comment]
I cloned https://github.com/curl/ 
I edited my previous comment a few days ago when I realized my reply wasn't accurate since I didn't download and unzip the tar.

**Comment by ctya** [comment]
Any feedback or can you please merge this?

**Comment by develCuy** [comment]
@ctya, can you use the official tarball provided in curl's website? Merging against a copy of git is not recommended since there are several files that might conflict with our codebase. Also, as stated before, I found several differences in the code you try to merge vs. the official tarball. Thanks for your understanding and keep up the good work!

**Comment by ctya** [comment]
I'll do that and open a new PR

**Pull request closed without merging**
